create table if not exists public.cash_sessions (
  id bigint generated by default as identity primary key,
  status text not null default 'OPEN' check (status in ('OPEN', 'CLOSED')),
  opening_amount numeric(12,2) not null check (opening_amount >= 0),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  counted_amount numeric(12,2) check (counted_amount >= 0),
  expected_amount numeric(12,2) check (expected_amount >= 0),
  difference numeric(12,2),
  notes text not null default '',
  close_notes text not null default '',
  constraint cash_sessions_closed_values check (
    (status = 'OPEN' and closed_at is null and counted_amount is null and expected_amount is null and difference is null)
    or
    (status = 'CLOSED' and closed_at is not null and counted_amount is not null and expected_amount is not null and difference is not null)
  )
);

create unique index if not exists cash_sessions_one_open_idx
  on public.cash_sessions (status)
  where status = 'OPEN';

create index if not exists cash_sessions_opened_at_idx
  on public.cash_sessions (opened_at desc);

create table if not exists public.cash_movements (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.cash_sessions(id) on delete cascade,
  movement_type text not null check (movement_type in ('IN', 'OUT')),
  amount numeric(12,2) not null check (amount > 0),
  reason text not null check (char_length(trim(reason)) between 2 and 160),
  created_at timestamptz not null default now()
);

create index if not exists cash_movements_session_created_idx
  on public.cash_movements (session_id, created_at desc);

alter table public.cash_sessions enable row level security;
alter table public.cash_movements enable row level security;

revoke all on table public.cash_sessions from anon, authenticated;
revoke all on table public.cash_movements from anon, authenticated;
grant select, insert, update, delete on table public.cash_sessions to service_role;
grant select, insert, update, delete on table public.cash_movements to service_role;
grant usage, select on sequence public.cash_sessions_id_seq to service_role;
grant usage, select on sequence public.cash_movements_id_seq to service_role;

alter table public.orders
  add column if not exists cash_session_id bigint references public.cash_sessions(id) on delete set null;

create index if not exists orders_cash_session_id_idx
  on public.orders (cash_session_id)
  where cash_session_id is not null;
