alter table public.products
  add column if not exists track_stock boolean not null default false,
  add column if not exists stock_quantity numeric(12,3),
  add column if not exists low_stock_threshold numeric(12,3) not null default 1;

alter table public.products
  drop constraint if exists products_stock_quantity_check,
  add constraint products_stock_quantity_check
    check (stock_quantity is null or stock_quantity >= 0),
  drop constraint if exists products_low_stock_threshold_check,
  add constraint products_low_stock_threshold_check
    check (low_stock_threshold >= 0);

create index if not exists products_inventory_alert_idx
  on public.products (stock_quantity)
  where track_stock and is_active;

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id),
  order_id uuid references public.orders(id),
  quantity_change numeric(12,3) not null check (quantity_change <> 0),
  resulting_stock numeric(12,3) not null check (resulting_stock >= 0),
  movement_type text not null check (movement_type in ('POS_SALE', 'MANUAL_ADJUSTMENT')),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists inventory_movements_product_created_idx
  on public.inventory_movements (product_id, created_at desc);

alter table public.inventory_movements enable row level security;
revoke all on table public.inventory_movements from anon, authenticated;
grant select, insert on table public.inventory_movements to service_role;
grant usage, select on sequence public.inventory_movements_id_seq to service_role;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.decrement_pos_inventory()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  sold record;
  tracked boolean;
  current_stock numeric(12,3);
  new_stock numeric(12,3);
begin
  if new.order_channel is distinct from 'POS' then
    return new;
  end if;

  for sold in
    select item->>'id' as product_id,
           sum((item->>'quantity')::numeric) as quantity
      from jsonb_array_elements(new.items) as item
     group by item->>'id'
  loop
    select p.track_stock, p.stock_quantity
      into tracked, current_stock
      from public.products as p
     where p.id = sold.product_id
     for update;

    if not found or not tracked then
      continue;
    end if;

    if current_stock is null or current_stock < sold.quantity then
      raise exception using
        errcode = 'P0001',
        message = 'INSUFFICIENT_STOCK:' || sold.product_id;
    end if;

    new_stock := current_stock - sold.quantity;
    update public.products
       set stock_quantity = new_stock,
           updated_at = now()
     where id = sold.product_id;

    insert into public.inventory_movements
      (product_id, order_id, quantity_change, resulting_stock, movement_type, note)
    values
      (sold.product_id, new.id, -sold.quantity, new_stock, 'POS_SALE', new.order_reference);
  end loop;

  return new;
end;
$$;

revoke execute on function private.decrement_pos_inventory() from public, anon, authenticated;

drop trigger if exists orders_decrement_pos_inventory on public.orders;
create trigger orders_decrement_pos_inventory
after insert on public.orders
for each row execute function private.decrement_pos_inventory();
