"use client";
import { FormEvent,useMemo,useState } from "react";
import styles from "./compras.module.css";
type Supplier={id:string;name:string;allows_cash:boolean;allows_credit:boolean}; type Product={id:string;name:string;unit:string;stock:number};
type Code={supplier_id:string;supplier_code:string;product_id:string|null;supplier_description:string|null};
type Receipt={id:string;receipt_number:string;supplier_id:string;payment_method:string;total_amount:number|string;received_at:string};
type Payable={id:string;supplier_id:string;outstanding_amount:number|string;due_date:string;status:string};
const empty={supplierId:"",productId:"",rawCode:"",supplierCode:"",description:"",quantity:"",unitCost:"",paymentMethod:"CASH",dueDate:"",lotNumber:"",packedAt:"",expiresAt:"",supplierDocument:"",notes:""};
const mxn=new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"});
export default function MerchandiseEntry({suppliers,codes,products,receipts,payables}:{suppliers:Supplier[];codes:Code[];products:Product[];receipts:Receipt[];payables:Payable[]}){
 const [form,setForm]=useState(empty),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const supplier=suppliers.find(x=>x.id===form.supplierId),product=products.find(x=>x.id===form.productId),total=Number(form.quantity||0)*Number(form.unitCost||0);
 const matched=useMemo(()=>codes.find(c=>c.supplier_id===form.supplierId&&c.supplier_code===form.rawCode.trim()),[codes,form.rawCode,form.supplierId]);
 const change=(key:string,value:string)=>setForm(prev=>({...prev,[key]:value})); const supplierName=(id:string)=>suppliers.find(s=>s.id===id)?.name||id;
 function identify(){if(!form.supplierId){setError("Primero selecciona el proveedor.");return}if(!form.rawCode.trim()){setError("Escanea o escribe el código.");return}setError("");if(matched){setForm(prev=>({...prev,productId:matched.product_id||prev.productId,supplierCode:matched.supplier_code,description:matched.supplier_description||prev.description}));setMessage(matched.product_id?"Código reconocido; producto seleccionado.":"Código reconocido. Selecciona una vez el producto para guardar la relación.");}else setMessage("Código nuevo. Selecciona el producto; al registrar, el sistema lo recordará.");}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");try{const res=await fetch("/api/admin/purchases",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),data=await res.json() as {error?:string;receiptNumber?:string;newStock?:number};if(!res.ok)throw new Error(data.error||"No se pudo registrar.");setMessage(`Entrada ${data.receiptNumber} guardada. Nueva existencia: ${Number(data.newStock).toLocaleString("es-MX",{maximumFractionDigits:3})} ${product?.unit||""}.`);setForm(prev=>({...empty,supplierId:prev.supplierId,paymentMethod:supplier?.allows_cash?"CASH":"CREDIT"}));}catch(err){setError(err instanceof Error?err.message:"No se pudo registrar.")}finally{setSaving(false)}}
 return <main className={styles.shell}><header><div><span>INVENTARIO Y COMPRAS</span><h1>Entrada de mercancía</h1><p>Escanea la etiqueta, confirma peso y costo, y aumenta la existencia.</p></div><nav><a href="/admin/admon">← Admon</a><a href="/admin/proveedores">Proveedores</a><a href="/admin/productos">Inventario</a><a href="/admin/pos">POS</a></nav></header>
 <section className={styles.layout}><form onSubmit={submit} className={styles.form}><div className={styles.step}><b>1</b><label>Proveedor<select required value={form.supplierId} onChange={e=>{const s=suppliers.find(x=>x.id===e.target.value);setForm({...empty,supplierId:e.target.value,paymentMethod:s?.allows_cash?"CASH":"CREDIT"})}}><option value="">Selecciona…</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>
 <div className={styles.scan}><label>Código leído por el escáner<input autoFocus value={form.rawCode} onChange={e=>change("rawCode",e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();identify()}}} placeholder="Escanea aquí y presiona Enter"/></label><button type="button" onClick={identify}>Identificar</button></div>
 <div className={styles.grid}><label>Producto del inventario<select required value={form.productId} onChange={e=>change("productId",e.target.value)}><option value="">Selecciona producto…</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.stock} {p.unit}</option>)}</select></label><label>Descripción del proveedor<input value={form.description} onChange={e=>change("description",e.target.value)} placeholder="Ej. Trozos de pierna"/></label><label>Peso o cantidad<input required type="number" min=".001" step=".001" value={form.quantity} onChange={e=>change("quantity",e.target.value)} placeholder="27.870"/></label><label>Costo por {product?.unit||"unidad"}<input required type="number" min="0" step=".01" value={form.unitCost} onChange={e=>change("unitCost",e.target.value)} placeholder="$0.00"/></label><label>Lote<input value={form.lotNumber} onChange={e=>change("lotNumber",e.target.value)}/></label><label>Factura/remisión<input value={form.supplierDocument} onChange={e=>change("supplierDocument",e.target.value)}/></label><label>Fecha de empaque<input type="date" value={form.packedAt} onChange={e=>change("packedAt",e.target.value)}/></label><label>Caducidad<input type="date" value={form.expiresAt} onChange={e=>change("expiresAt",e.target.value)}/></label></div>
 <div className={styles.payment}><button type="button" disabled={!supplier?.allows_cash} className={form.paymentMethod==="CASH"?styles.active:""} onClick={()=>change("paymentMethod","CASH")}>💵 Contado</button><button type="button" disabled={!supplier?.allows_credit} className={form.paymentMethod==="CREDIT"?styles.active:""} onClick={()=>change("paymentMethod","CREDIT")}>🕐 Crédito</button>{form.paymentMethod==="CREDIT"&&<label>Fecha para pagar<input required type="date" value={form.dueDate} onChange={e=>change("dueDate",e.target.value)}/></label>}</div>
 <label>Notas<input value={form.notes} onChange={e=>change("notes",e.target.value)} placeholder="Observaciones opcionales"/></label>{error&&<p className={styles.error}>{error}</p>}{message&&<p className={styles.success}>{message}</p>}<div className={styles.total}><span>Total de la compra</span><strong>{mxn.format(total||0)}</strong></div><button className={styles.save} disabled={saving}>{saving?"Guardando…":"Registrar entrada y aumentar inventario"}</button></form>
 <aside><section><h2>Cuentas por pagar</h2>{payables.length?payables.map(p=><article key={p.id}><div><strong>{supplierName(p.supplier_id)}</strong><small>Vence {new Date(p.due_date+"T12:00:00").toLocaleDateString("es-MX")}</small></div><b>{mxn.format(Number(p.outstanding_amount))}</b></article>):<p>No hay compras pendientes.</p>}</section><section><h2>Entradas recientes</h2>{receipts.map(r=><article key={r.id}><div><strong>{r.receipt_number}</strong><small>{supplierName(r.supplier_id)} · {r.payment_method==="CREDIT"?"Crédito":"Contado"}</small></div><b>{mxn.format(Number(r.total_amount))}</b></article>)}</section></aside></section></main>
}
